[package]
name = "dashboard"
version = "0.1.2"
edition = "2021"

[[bin]]
name = "dashboard_bin"
path = "src/main.rs"

[features]
default = []
bundled = ["rusqlite/bundled"]

[dependencies]
rand = "0.8"
dirs = "4"
git-version = "0.3.5"
chrono = { version = "0.4", features = ["wasmbind"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.27" }
jql = { version = "4", default-features = false }
ureq = { version = "2", features = ["json"] }
eframe = { version = "0.18", features = ["persistence"] }