[package]
name = "dashboard"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dashboard_bin"
path = "src/main.rs"

[dependencies]
rand = "0.8"
dirs = "4"
git-version = "0.3.5"
chrono = { version = "0.4", features = ["wasmbind"] }
eframe = { version = "0.18", features = ["persistence"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.27" }
jq-rs = "0.4"
ureq = { version = "2", features = ["json"] }

[env]
JQ_LIB_DIR="/usr/lib"
