[package]
name = "dashboard"
version = "0.1.2"
edition = "2021"

[[bin]]
name = "dashboard_bin"
path = "src/main.rs"

[features]
default = ["bundled"]
bundled = ["rusqlite/bundled"]
web = ["chrono/wasmbind", "eframe/persistence"]

[dependencies]
rand = "0.8"
dirs = "4"
git-version = "0.3.5"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = "0.27"
jql = { version = "4", default-features = false }
ureq = { version = "2", features = ["json"] }
eframe = "0.18"